workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    integrations:
      app_store_connect: Codemagic
    environment:
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.jbpaladinpatriotsclock.jbpaladinpatriotsclock
      vars:
        APP_STORE_APPLE_ID: "XAJF22HXCQ"
        XCODE_WORKSPACE: "JbPaladinPatriotsClock.xcworkspace" # Update with actual workspace name
        XCODE_SCHEME: "JbPaladinPatriotsClock" # Update with actual scheme name
    scripts:
      - name: Update Ruby Version
        script: |
          ruby -v
          brew install ruby
          export PATH="/usr/local/opt/ruby/bin:$PATH"
          echo 'export PATH="/usr/local/opt/ruby/bin:$PATH"' >> ~/.zshrc
          ruby -v  # Check new Ruby version

      - name: Install npm dependencies for Cordova
        script: | 
          npm install

      - name: Install CocoaPods
        script: | 
          sudo gem install cocoapods -v 1.12.0  # Use an updated version

      - name: CocoaPods installation
        script: | 
          cd platforms/ios && pod install || pod install --repo-update

      - name: Set up code signing settings on Xcode project
        script: | 
          xcode-project use-profiles

      - name: Build ipa for distribution
        script: | 
          cd platforms/ios
          xcodebuild -workspace "$XCODE_WORKSPACE" \
                     -scheme "$XCODE_SCHEME" \
                     -configuration Release \
                     archive -archivePath build/App.xcarchive

      - name: Export .ipa file
        script: | 
          xcodebuild -exportArchive \
                     -archivePath build/App.xcarchive \
                     -exportOptionsPlist exportOptions.plist \
                     -exportPath build/ \
                     -allowProvisioningUpdates

    artifacts:
      - platforms/ios/build/device/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
