workflows:
  ios-build:
    name: iOS Build
    environment:
      xcode: latest
      node: 14
    scripts:
      - name: Install Dependencies
        script: |
          npm install
      - name: Build Cordova App
        script: |
          cordova build ios --release --device
    artifacts:
      - platforms/ios/build/device/*.ipa
