workflows:
  ios-development-workflow:
    name: iOS Development Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        APP_STORE_CONNECT_API_KEY: $APP_STORE_CONNECT_API_KEY
       APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
    scripts:
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" --platform IOS --type IOS_APP_DEVELOPMENT --create
      - name: Build IPA for development
        script: |
          xcodebuild -workspace "YourApp.xcworkspace" \
          -scheme "YourAppScheme" \
          -configuration Debug \  # Use Debug configuration for development
          -archivePath build/YourApp.xcarchive archive
          xcodebuild -exportArchive \
          -archivePath build/YourApp.xcarchive \
          -exportPath build/YourApp.ipa \
          -exportOptionsPlist ExportOptions.plist
    artifacts:
      - build/*.ipa
