workflows:
  ios-build:
    name: iOS Build
    environment:
      xcode: latest
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios
          pod install
      - name: Build the app
        script: |
          cd ios
          xcodebuild -workspace YourApp.xcworkspace -scheme YourApp -configuration Release -archivePath build/YourApp.xcarchive archive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive -archivePath build/YourApp.xcarchive -exportPath build -exportOptionsPlist exportOptions.plist
    artifacts:
      - build/*.ipa
    publishing:
      email:
        recipients:
          - jbpaladin122@gmail.com
