workflows:
  ios-build:
    name: iOS Build with Provisioning Profile
    max_build_duration: 120
    environment:
      node: 14 # Specify the Node.js version you need
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Add iOS platform
        script: |
          cordova platform add ios --save
      - name: Install CocoaPods dependencies
        script: |
          cd platforms/ios && pod install
      - name: Build the app
        script: |
          cordova build ios --release --device --codeSignIdentity="iPhone Distribution" --provisioningProfile="my_app_distribution_profile"
    code_signing:
      distribution:
        method: app-store
        profile: my_app_distribution_profile # Your provisioning profile name
        certificate: Distribution Certificate # Your distribution certificate name
    artifacts:
      - platforms/ios/build/device/*.ipa # Adjust the path if necessary
