workflows:
  cordova_ios_build:
    name: Cordova iOS Build
    instance_type: mac_mini_m2  # Use Mac Mini M2 for better performance
    environment:
      vars:
        XCODE_WORKSPACE: "platforms/ios/JbPaladinPatriotsClock.xcworkspace"
        XCODE_SCHEME: "JbPaladinPatriotsClock" # Replace with your app's scheme name
        BUNDLE_ID: "com.jbpaladinpatriotsclock.jbpaladinpatriotsclock" # Update with your Bundle ID
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install Cordova
        script: |
          npm install -g cordova
          npm install

      - name: Add iOS Platform
        script: |
          cordova platform add ios

      - name: Build iOS App
        script: |
          cordova build ios --release --device

      - name: Prepare for Code Signing
        script: |
          # Ensure correct provisioning profile is used
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PROVISIONING_PROFILE ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Set up code signing settings on Xcode project
        script: | 
          xcode-project use-profiles  # Set up code signing profiles

      - name: Export Signed IPA
        script: |
          cd platforms/ios
          xcodebuild -workspace "$XCODE_WORKSPACE" \
                     -scheme "$XCODE_SCHEME" \
                     -sdk iphoneos \
                     -configuration Release \
                     archive -archivePath $CM_BUILD_DIR/build/App.xcarchive

          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/build/App.xcarchive \
                     -exportOptionsPlist exportOptions.plist \
                     -exportPath $CM_BUILD_DIR/build

      - name: Save Artifacts
        script: |
          mv $CM_BUILD_DIR/build/*.ipa $CM_ARTIFACTS_DIR/

artifacts:
  - build/*.ipa
