workflows:
  ios-release:
    name: Build iOS Release
    platform: ios
    flutter: false  # Set to false if you're not using Flutter
    xcode: true  # Indicate that it uses Xcode to build the app
    scripts:
      - name: Install Dependencies
        script: |
          npm install
          brew install node
          npm install -g cordova
      - name: Build Cordova Project
        script: |
          cordova platform add ios
          cordova build ios --release --device
    artifacts:
      - build/ios/platforms/ios/build/device/*.ipa
