workflows:
  ios-workflow:
    name: Ionic Cordova iOS Workflow
    max_build_duration: 120
    environment:
      ios_signing:
        distribution_type: app_store  
        bundle_identifier: com.jbpaladinpatriotsclock.jbpaladinpatriotsclock  # Update with your app's bundle ID
      node: latest  # Use the latest Node.js version
    scripts:
      - name: Install npm dependencies and update Cordova version
        script: | 
          npm install
          npm ci  # equivalent of npm install for CI systems
          cvm install 9.0.0  # Specify the Cordova version you want to use
          cvm use 9.0.0 
      - name: Setup Cordova iOS platform
        script: | 
        cordova platform remove ios --nosave
        cordova platform add ios \
            --confirm \
            --no-interactive \
            --noresources 
      - name: Build iOS Cordova App
        script: | 
          ionic cordova build ios \
            --release \
            --no-interactive \
            --prod \
            --device
      - name: Export IPA
        script: | 
          # Specify the path to the generated IPA file
          IPA_PATH=$(find platforms/ios/build/device -name "*.ipa" | head -1)
          echo "IPA Path: $IPA_PATH"
    artifacts:
      - platforms/ios/build/device/**/*.ipa  # Adjust the path based on where the IPA is generated
 
