workflows:
  ios-release:
    name: Build iOS Release
    platform: ios
    scripts:
      - name: Install Dependencies
        script: |
          npm install
          npm install -g cordova
      - name: Build Cordova Project
        script: |
          cordova platform add ios
          cordova build ios --release --device
