workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    integrations:
      app_store_connect: Codemagic
    environment:
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.jbpaladinpatriotsclock.jbpaladinpatriotsclock
      vars:
        APP_STORE_APPLE_ID: "XAJF22HXCQ"
        XCODE_WORKSPACE: "JbPaladinPatriotsClock.xcworkspace"
        XCODE_SCHEME: "JbPaladinPatriotsClock"
    scripts:
      - name: Switch to System Ruby
        script: |
          set -e
          if command -v rvm > /dev/null; then
            rvm use system
          elif command -v chruby > /dev/null; then
            chruby system
          fi
          echo "Using Ruby version:"
          ruby -v

      - name: Install npm dependencies
        script: |
          set -e
          npm install

      - name: Add iOS platform
        script: |
          set -e
          cordova platform add ios@latest

      - name: Install CocoaPods
        script: |
          set -e
          gem install cocoapods -v 1.12.0
          if [ -f platforms/ios/Podfile ]; then
            cd platforms/ios
            pod install || pod install --repo-update
          fi

      - name: Clean Build
        script: |
          set -e
          echo "Cleaning previous build artifacts..."
          cordova clean ios

      - name: Set up code signing settings on Xcode project
        script: |
          set -e
          xcode-project use-profiles

      - name: Build iOS App
        script: |
          set -e
          cordova build ios --release --device

      - name: Create Xcode Archive
        script: |
          set -e
          xcodebuild archive \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -archivePath output/JbPaladinPatriotsClock.xcarchive \
            -configuration Release \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM=$CM_DEVELOPER_TEAM \
            PROVISIONING_PROFILE_SPECIFIER="$CM_PROVISIONING_PROFILE"

      - name: Export IPA File
        script: |
          set -e
          mkdir -p output
          xcodebuild -exportArchive \
            -archivePath output/JbPaladinPatriotsClock.xcarchive \
            -exportOptionsPlist platforms/ios/exportOptions.plist \
            -exportPath output

    artifacts:
      - output/*.ipa  
      - output/JbPaladinPatriotsClock.xcarchive
      - platforms/ios/build/device/*.app
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
