workflows:
  ios-build:
    name: iOS Build
    environment:
      xcode: latest
    scripts:
      - name: Install Node.js and Cordova
        script: |
          brew install node
          npm install -g cordova
      - name: Install Cordova iOS platform
        script: |
          cordova platform add ios
      - name: Build iOS
        script: |
          cordova build ios --release --device
    artifacts:
      - platforms/ios/build/device/*.ipa
