workflows:
  ios-build:
    name: iOS Build
    environment:
      xcode: latest  # Use the latest version of Xcode
      node: latest
    scripts:
      - name: Install Dependencies
        script: |
          npm install
          npm install -g cordova
          cordova platform add ios

      - name: Build iOS App
        script: |
          cordova build ios --release --device --codeSignIdentity="iPhone Distribution" --provisioningProfile="MyApp Distribution Profile"

    artifacts:
      - platforms/ios/build/device/*.ipa   # Adjust this path as needed
