workflows:
  ios-workflow:
    name: iOS Build
    environment:
      xcode: latest
    scripts:
      - name: Build IPA for distribution
        script: |
          cd platforms/ios
          xcodebuild -workspace JbPaladinPatriotsClock.xcworkspace -scheme YourAppScheme -configuration Release -archivePath build/JbPaladinPatriotsClock.xcarchive archive
          xcodebuild -exportArchive -archivePath build/JbPaladinPatriotsClock.xcarchive -exportPath build -exportOptionsPlist exportOptions.plist
    artifacts:
      - platforms/ios/build/*.ipa
