workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.example.id
    scripts:
      - name: Set up code signing settings
        script: xcode-project use-profiles
      - name: Build IPA
        script: xcode-project build-ipa --workspace "YourApp.xcworkspace" --scheme "YourApp"
