workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.jbpaladinpatriotsclock.jbpaladinpatriotsclock
      xcode: latest
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install -g cordova
          npm install
      - name: Build iOS
        script: |
          cordova platform add ios
      - name: Update CordovaLib Deployment Target
        script: |
          # Update the deployment target for CordovaLib
          sed -i '' 's/11.0/12.0/g' platforms/ios/CordovaLib/CordovaLib.xcodeproj/project.pbxproj
      - name: Set up code signing settings on Xcode project
        script: | 
          xcode-project use-profiles  # Set up code signing profiles
      - name: Build iOS
        script: |
          cordova build ios --release --device
    artifacts:
      - build/ios/*.ipa
