workflows:
  cordova_ios_build:
    name: Cordova iOS Build
    instance_type: mac_mini_m2  # Use Mac Mini M2 for better performance
    environment:
      vars:
        XCODE_WORKSPACE: "platforms/ios/JbPaladinPatriotsClock.xcworkspace"
        XCODE_SCHEME: "JbPaladinPatriotsClock" # Replace with your app's scheme name
        BUNDLE_ID: "com.jbpaladinpatriotsclock.jbpaladinpatriotsclock" # Update with your Bundle ID
        APP_STORE_TEAM_ID: "XAJF22HXCQ" # Your Apple Developer Team ID
        PROVISIONING_PROFILE: "YOUR_PROFILE_UUID_HERE" # UUID of your profile
        PROVISIONING_PROFILE_SPECIFIER: "JbPaladinPatriotsClock Distribution Profile"
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install Cordova
        script: |
          npm install -g cordova
          npm install

      - name: Add iOS Platform
        script: |
          cordova platform add ios

      - name: Set iOS Deployment Target to 12.0
        script: |
          find platforms/ios -name "project.pbxproj" -print0 | xargs -0 sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 11.0;/IPHONEOS_DEPLOYMENT_TARGET = 12.0;/g'

      - name: Set up code signing settings on Xcode project
        script: | 
          xcode-project use-profiles

      - name: Build iOS App
        script: |
          cordova build ios --release --device

      - name: Export Signed IPA
        script: |
          cd platforms/ios
          xcodebuild -workspace "$XCODE_WORKSPACE" \
                     -scheme "$XCODE_SCHEME" \
                     -sdk iphoneos \
                     -configuration Release \
                     archive -archivePath $CM_BUILD_DIR/build/App.xcarchive

          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/build/App.xcarchive \
                     -exportOptionsPlist exportOptions.plist \
                     -exportPath $CM_BUILD_DIR/build

      - name: Save Artifacts
        script: |
          mv $CM_BUILD_DIR/build/*.ipa $CM_ARTIFACTS_DIR/

artifacts:
  - build/*.ipa
