workflows:
  ios-build:
    name: iOS Build
    environment:
      xcode: latest
      node: 14
    scripts:
      - name: Install Dependencies
        script: |
          npm install
      - name: Build Cordova App
        script: |
          cordova build ios --release --device
    artifacts:
      - platforms/ios/build/device/*.ipa
    code-signing:
      # Use the correct format for automatic code signing
      identity: "iPhone Distribution: Jeffrey Wayne Birge"
      provisioning_profile: "my_app_distribution_profile"
      team_id: "XAJF22HXCQ"
