workflows:
  ios-workflow:
    name: iOS Build
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build iOS
        script: |
          cordova build ios --release
    artifacts:
      - build/ios/*.ipa
