workflows:
  ios-workflow:
    name: iOS Build Workflow
    environment:
      vars:
        BUNDLE_ID: com.jbpaladinpatriotsclock.jbpaladinpatriotsclock
      node: latest
    scripts:
      - name: Install Cordova
        script: npm install -g cordova
      - name: Add iOS Platform
        script: cordova platform add ios
      - name: Build iOS
        script: cordova build ios --release --device
    artifacts:
      - build/ios/ipa/*.ipa
