workflows:
  ios-workflow:
    name: iOS Cordova Workflow
    max_build_duration: 120
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.jbpaladinpatriotsclock.jbpaladinpatriotsclock
        development_team: "XAJF22HXCQ"  
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
          npm ci
      - name: Setup Cordova iOS platform
        script: |
          cordova platform remove ios --nosave
          cordova platform add ios --save
      - name: Build the iOS app
        script: |
          cordova build ios --release --device
    artifacts:
      - platforms/ios/build/device/*.ipa
