workflows:
  ios-release:
    name: Build iOS Release
    scripts:
      - name: Install Dependencies
        script: |
          npm install
          brew install node
          npm install -g cordova
      - name: Build Cordova Project
        script: |
          cordova platform add ios
          cordova build ios --release --device
    artifacts:
      - build/ios/platforms/ios/build/device/*.ipa
