workflows:
  ios-workflow:
    name: iOS Manual Signing
    environment:
      vars:
        CODE_SIGN_IDENTITY: "iPhone Distribution"
    scripts:
      - npm install
      - cordova prepare ios
      - cordova build ios --release
    build:
      ios:
        code_signing:
          method: manual
          certificate: comnbined.p12
          provisioning_profile: jbpaladin.mobileprovision
