workflows:
  ios-workflow:
    name: Cordova iOS Workflow
    max_build_duration: 120
    environment:
      ios_signing:
        distribution_type: app_store  
        bundle_identifier: com.jbpaladinpatriotsclock.jbpaladinpatriotsclock
        development_team: XAJF22HXCQ
      node: latest  # Use the latest Node.js version
    scripts:
      - name: Install npm dependencies and update Cordova version
        script: | 
          npm install
          npm ci  # equivalent of npm install for CI systems
          cvm install 12.0.0  # Specify Cordova version 12
          cvm use 12.0.0 
      - name: Update iOS Deployment Target
        script: |
          sed -i '' 's/<preference name="deployment-target" value=".*" \/>/<preference name="deployment-target" value="12.0" \/>/' config.xml
      - name: Clean Build Directory
        script: |
          rm -rf platforms/ios/build
      - name: Setup Cordova iOS platform
        script: | 
          cordova platform remove ios --nosave
          cordova platform add ios \
            --confirm \
            --no-interactive \
            --noresources 
      - name: Build iOS Cordova App
        script: | 
          cordova build ios \
            --release \
            --no-interactive \
            --prod \
            --device \
            --verbose
      - name: Export IPA
        script: | 
          IPA_PATH=$(find platforms/ios/build/device -name "*.ipa" | head -1)
          echo "IPA Path: $IPA_PATH"
    artifacts:
      - platforms/ios/build/device/**/*.ipa  # Adjust the path based on where the IPA is generated
