workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.jbpaladinpatriotsclock.jbpaladinpatriotsclock
        development_team: XAJF22HXCQ
      xcode: latest
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install -g cordova
          npm install
      - name: Set up code signing settings on Xcode project
        script: | 
          xcode-project use-profiles  # Set up code signing profiles
      - name: Build iOS
        script: |
          cordova platform add ios
          cordova build ios --release --device
    artifacts:
      - build/ios/*.ipa
