workflows:
  ios-workflow:
    name: iOS Build
    environment:
      xcode: latest
    scripts:
      - name: Build IPA for distribution
        script: |
          xcode-project build-ipa \
          --workspace "YourApp.xcworkspace" \
          --scheme "YourAppScheme"
    artifacts:
      - build/ios/ipa/*.ipa
