workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    environment:
      groups:
        - ios_credentials
        - appstore_credentials
      ios_signing:
        provisioning_profiles:
          - Ad hoc Profile
        certificates:
          - JbPaladin Certificate
    scripts:
      - name: Install npm dependencies and update Cordova version
        script: | 
          npm install
          npm install -g cordova

      - name: Remove Cordova splash screen plugin
        script: | 
          cordova plugin rm cordova-plugin-splashscreen --nosave || echo "No splash plugin found"

      - name: Setup Cordova iOS platform
        script: | 
          cordova platform remove ios --nosave
          cordova platform add ios \
            --confirm \
            --no-interactive \
            --noresources \
            --save

      - name: Copy custom icons to the Xcode project
        script: | 
          APP_ICON_PATH="res/icon/ios/"
          IOS_PLATFORM_PATH="platforms/ios/JbPaladinPatriotsClock/Images.xcassets/AppIcon.appiconset/"

          if [ -d "$APP_ICON_PATH" ]; then
            cp -R "$APP_ICON_PATH" "$IOS_PLATFORM_PATH"
            echo "✅ Custom app icons copied successfully."
          else
            echo "⚠️ Custom app icons folder not found!"
          fi

      - name: Set up code signing settings on Xcode project
        script: | 
          xcode-project use-profiles --project platforms/ios/JbPaladinPatriotsClock.xcodeproj

      - name: Build ipa for distribution
        script: | 
          cat /Users/builder/export_options.plist
          package_type=$(defaults read /Users/builder/export_options.plist method)
          identity=$(defaults read /Users/builder/export_options.plist signingCertificate)
          team=$(defaults read /Users/builder/export_options.plist teamID)
          profile=$(find '/Users/builder/Library/MobileDevice/Provisioning Profiles' -name "*.mobileprovision")
          profile_uuid=$(grep UUID -A1 -a "$profile" | grep -io "[-A-F0-9]\{36\}")

          cat > build.json <<EOF
          {
            "ios": {
              "release": {
                "codeSignIdentity": "$identity",
                "developmentTeam": "$team",
                "packageType": "$package_type",
                "provisioningProfile": "$profile_uuid"
              }
            }
          }
          EOF
          cordova build ios --release --device --buildConfig='build.json'

    # Remove TestFlight upload step
    publishing:
      email:
        recipients:
          - diane.c.yap@gmail.com
          - ehllenjoyquezada.creative@gmail.com
          - anapatricia.mendoza00@gmail.com
        notify:
          success: true
          failure: false

    artifacts:
      - /Users/builder/clone/platforms/ios/build/Release-iphoneos/JbPaladinPatriotsClock.ipa
      - /tmp/xcodebuild_logs/*.log
