workflows:
  cordova-ios-workflow:
    name: Cordova iOS Workflow
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.example.cordovaapp  # Replace with your actual bundle identifier
        development_team: XAJF22HXCQ  # Your Team ID
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Add iOS platform
        script: |
          cordova platform add ios
      - name: Build IPA for distribution
        script: |
          cordova build ios --release --device
    artifacts:
      - platforms/ios/build/device/*.ipa
