workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.jbpaladinpatriotsclock.jbpaladinpatriotsclock
    scripts:
      - name: Install npm dependencies
        script: | 
          npm install
          npm ci
          npm install -g cordova@latest

      - name: Add iOS platform
        script: | 
          cordova platform add ios --save
      
      - name: Build iOS app
        script: |
          cordova build ios --release --device --buildConfig='build.json'

    artifacts:
      - platforms/ios/build/device/*.ipa
      - /tmp/xcodebuild_logs/*.log
