workflows:
  ios-build:
    name: iOS Build
    environment:
      node: 14 # Specify your Node.js version
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install -g cordova
      - name: Build Cordova App
        script: |
          cordova build ios --release --device
    ios:
      code_sign_identity: "iPhone Distribution: Jeffrey Wayne Birge (XAJF22HXCQ)"
      provisioning_profile: "my_app_distribution_profile"
      signing_certificate: "distribution.p12"
      apple_developer_account: "jbpaladin122@gmail.com"
      # Optional: specify the build configuration (Debug/Release)
      build_configuration: "Release"
    artifacts:
      - platforms/ios/build/device/YourAppName.ipa
