workflows:
  ios_native_workflow:
    name: iOS Native Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.jbpaladinpatriotsclock.jbpaladinpatriotsclock
      vars:
        APP_STORE_APPLE_ID: XAJF22HXCQ
        XCODE_WORKSPACE: "platforms/ios/JbPaladinPatriotsClock.xcworkspace"
        XCODE_SCHEME: "JbPaladinPatriotsClock"
    scripts:
      - name: Install npm Dependencies
        script: |
          npm install  # Install npm dependencies needed for your project
      - name: Remove iOS Platform
        script: |
          cordova platform rm ios
      - name: Add iOS Platform
        script: |
          cordova platform add ios@latest
      - name: Prepare iOS Platform
        script: |
          cordova prepare ios
      - name: Build IPA for Distribution
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --export-options-plist "$CM_BUILD_DIR/export_options.plist" \
            --configuration Release  # Ensure we are building the release version
    artifacts:
      - build/ios/ipa/*.ipa  # Path to the generated IPA files
      - /tmp/xcodebuild_logs/*.log  # Path to Xcode build logs
