workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    integrations:
      app_store_connect: Codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.jbpaladinpatriotsclock.jbpaladinpatriotsclock
    scripts:
      - name: Install npm dependencies and update Cordova version
        script: | 
          npm install
          npm ci # equivalent of npm install for CI systems.
            # Requires package-lock.json or npm-shrinkwrap.json to be present
          npm install -g cordova@12.0.0 # Install Cordova version 12
          cordova -v # Check Cordova version
      - name: Setup Cordova iOS platform
        script: | 
          cordova platform remove ios --nosave
          cordova platform add ios \
            --confirm \
            --no-interactive \
            --noresources \
            --save
      - name: Set up code signing settings on Xcode project
        script: | 
          xcode-project use-profiles
      - name: Build ipa for distribution
        script: | 
          package_type=$(defaults read ~/export_options.plist method)
          identity="iPhone Distribution: Distribution Certificate" 
          team="XAJF22HXCQ"
          
          # Get the provisioning profile name from the plist
          profile_name=$(defaults read ~/export_options.plist provisioningProfiles | grep -A1 "com.jbpaladinpatriotsclock.jbpaladinpatriotsclock" | tail -n1 | xargs)
          profile=$(find '/Users/builder/Library/MobileDevice/Provisioning Profiles' -name "*.mobileprovision" | grep "$profile_name")
          profile_uuid=$(grep UUID -A1 -a "$profile" | grep -io "[-A-F0-9]\{36\}")

          # Debug output
          echo "Package Type: $package_type"
          echo "Identity: $identity"
          echo "Team: $team"
          echo "Profile Name: $profile_name"
          echo "Profile UUID: $profile_uuid"

          # Create build.json
          cat <<EOF > build.json
          {
            "ios": {
              "release": {
                "codeSignIdentity": "$identity",
                "developmentTeam": "$team",
                "packageType": "$package_type",
                "provisioningProfile": "$profile_uuid"
              }
            }
          }EOF

          # Build the iOS app
          cordova build ios --release --device --buildConfig='build.json'
    artifacts:
      - platforms/ios/build/device/*.ipa
      - /tmp/xcodebuild_logs/*.log
