workflows:
  ios_native_workflow:
    name: iOS Native Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.jbpaladinpatriotsclock.jbpaladinpatriotsclock
        APP_STORE_APPLE_ID: XAJF22HXCQ
        XCODE_PROJECT: "platforms/ios/JbPaladinPatriotsClock.xcodeproj"
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
          npm ci
      - name: Remove and re-add iOS platform
        script: |
          cordova platform remove ios
          cordova platform add ios
      - name: Build the app
        script: | 
          cordova build ios --release --device
      - name: Create archive
        script: |
          xcodebuild -project platforms/ios/JbPaladinPatriotsClock.xcodeproj -scheme "JbPaladinPatriotsClock" -archivePath platforms/ios/build/device/JbPaladinPatriotsClock.xcarchive archive
      - name: Export ipa for distribution
        script: | 
          xcodebuild -exportArchive \
            -archivePath platforms/ios/build/device/JbPaladinPatriotsClock.xcarchive \
            -exportPath /Users/builder/clone/platforms/ios/build/device \
            -exportOptionsPlist ./export_options.plist
    artifacts:
      - /Users/builder/clone/platforms/ios/build/device/*.ipa
      - /tmp/xcodebuild_logs/*.log
