workflows:
  ios-build:
    name: iOS Build
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install -g cordova
    environment:
      node: 14 # Specify your Node.js version
    ios:
      build_configuration: "Release"
    artifacts:
      - build/ios/YourAppName.ipa
