workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.jbpaladinpatriotsclock.jbpaladinpatriotsclock
        development_team: XAJF22HXCQ
    scripts:
      - name: Clean up previous builds
        script: |
          rm -rf platforms plugins
      - name: Install npm dependencies
        script: |
          npm install
          npm ci
      - name: Setup Cordova iOS platform
        script: |
          cordova platform add ios --confirm --no-interactive
      - name: Build IPA for distribution
        script: |
          cordova build ios --release --device
    artifacts:
      - build/ios/ipa/*.ipa
