workflows:
  ios-workflow:
    name: iOS Manual Signing
    environment:
      vars:
        CODE_SIGN_IDENTITY: "iPhone Distribution"
    scripts:
      - npm install
      - cordova prepare ios
      - cordova build ios --release
    ios:
      code_signing:
        method: manual
        certificate: combined.p12
        provisioning_profile: jbpaladin.mobileprovision
