workflows:
  cordova_ios_build:
    name: Cordova iOS Build
    instance_type: mac_mini_m2
    environment:
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install Cordova and dependencies
        script: |
          npm install -g cordova
          npm install

      - name: Ensure iOS Platform is Added
        script: |
          cordova platform rm ios || true   # Remove iOS platform if it exists
          cordova platform add ios
          cordova prepare ios               # Ensure dependencies are installed

      - name: Install CocoaPods Dependencies
        script: |
          cd platforms/ios
          pod install --verbose

      - name: Check if iOS workspace exists
        script: |
          if [ ! -d "platforms/ios" ] || [ ! -f "platforms/ios/*.xcworkspace" ]; then
            echo "ERROR: iOS workspace does not exist!"
            exit 1
          fi

      - name: Set up code signing settings on Xcode project
        script: | 
          xcode-project use-profiles  

      - name: Build and Archive iOS App
        script: |
          cd platforms/ios
          xcodebuild -workspace *.xcworkspace \
                     -scheme "$(ls *.xcodeproj | cut -d. -f1)" \
                     -configuration Release \
                     archive -archivePath $CM_BUILD_DIR/build/App.xcarchive

      - name: Export Signed IPA
        script: |
          cd platforms/ios
          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/build/App.xcarchive \
                     -exportOptionsPlist exportOptions.plist \
                     -exportPath $CM_BUILD_DIR/build

      - name: Save Artifacts
        script: |
          mv $CM_BUILD_DIR/build/*.ipa $CM_ARTIFACTS_DIR/

artifacts:
  - build/*.ipa
