workflows:
  cordova_ios_build:
    name: Cordova iOS Build
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_WORKSPACE: "platforms/ios/JbPaladinPatriotsClock.xcworkspace"
        XCODE_SCHEME: "JbPaladinPatriotsClock"
        BUNDLE_ID: "com.jbpaladinpatriotsclock.jbpaladinpatriotsclock"
        DEVELOPMENT_TEAM: "XAJF22HXCQ"
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install Cordova
        script: |
          npm install -g cordova
          npm install

      - name: **Ensure iOS Platform is Added**
        script: |
          cordova platform rm ios || true   # Remove iOS platform if it exists
          cordova platform add ios

      - name: Check if iOS workspace exists
        script: |
          if [ ! -f "$XCODE_WORKSPACE" ]; then
            echo "ERROR: iOS workspace does not exist!"
            exit 1
          fi

      - name: Set up code signing settings on Xcode project
        script: | 
          xcode-project use-profiles  

      - name: Configure Xcode project with Development Team
        script: |
          cd platforms/ios
          xcodebuild -workspace "$XCODE_WORKSPACE" \
                     -scheme "$XCODE_SCHEME" \
                     -configuration Release \
                     DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
                     CODE_SIGN_IDENTITY="Apple Distribution" \
                     archive -archivePath $CM_BUILD_DIR/build/App.xcarchive

      - name: Export Signed IPA
        script: |
          cd platforms/ios
          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/build/App.xcarchive \
                     -exportOptionsPlist exportOptions.plist \
                     -exportPath $CM_BUILD_DIR/build

      - name: Save Artifacts
        script: |
          mv $CM_BUILD_DIR/build/*.ipa $CM_ARTIFACTS_DIR/

artifacts:
  - build/*.ipa
