workflows:
  ionic-cordova-ios-app:
    name: Ionic Cordova iOS App
    environment:
      vars:
        XCODE_WORKSPACE: "jbpaladinpatriotsclock.xcworkspace"
        XCODE_SCHEME: "jbpaladinpatriotsclock"
    scripts:
      - npm install
      - ionic cordova platform add ios --no-interactive
      - cd platforms/ios
      - xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
