workflows:
  cordova-workflow:
    name: Cordova Build
    environment:
      xcode: latest
      node: latest
    scripts:
      - name: Install Cordova dependencies
        script: |
          npm install
      - name: Build Android app
        script: |
          cordova build android --release
      - name: Build iOS app
        script: |
          cordova build ios --release
    artifacts:
      - platforms/android/app/build/outputs/apk/release/*.apk
      - platforms/ios/build/device/*.ipa
