workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    integrations:
      app_store_connect:  # This line defines the integration
        auth: integration  # This tells Codemagic to use the integration you set up
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.jbpaladinpatriotsclock.jbpaladinpatriotsclock
    scripts:
      - name: Install npm dependencies and update Cordova version
        script: | 
          npm install
          npm ci
          cvm install 9.0.0
          cvm use 9.0.0
          npm install -g ionic
          ionic info  
      - name: Setup Cordova iOS platform
        script: | 
          ionic cordova platform remove ios --nosave
          ionic cordova platform add ios \
            --confirm \
            --no-interactive \
            --noresources \
            --save
      - name: Set up code signing settings on Xcode project
        script: | 
          xcode-project use-profiles
      - name: Build ipa for distribution
        script: | 
          package_type=$(defaults read ~/export_options.plist method)
          identity=$(defaults read ~/export_options.plist signingCertificate)
          team=$(defaults read ~/export_options.plist teamID)
          profile=$(find '/Users/builder/Library/MobileDevice/Provisioning Profiles' -name "*.mobileprovision")
          profile_uuid=$(grep UUID -A1 -a "$profile" | grep -io "[-A-F0-9]\{36\}")

          cat <<EOF > build.json
          {
            "ios": {
              "release": {
                "codeSignIdentity": "$identity",
                "developmentTeam": "$team",
                "packageType": "$package_type",
                "provisioningProfile": "$profile_uuid"
              }
            }
          }EOF
          cordova build ios --release --device --buildConfig='build.json'
    artifacts:
      - /Users/builder/clone/platforms/ios/build/device/*.ipa
      - /tmp/xcodebuild_logs/*.log 
    publishing:
      email:
        recipients:
          - jbpaladin122@gmail.com
          - ehllenjoyquezada.creative@gmail.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration  # This should reference the integration you set up

        # Configuration related to TestFlight (optional)
        submit_to_testflight: true
        beta_groups:
          - group name 1
          - group name 2

        # Configuration related to App Store (optional)
        submit_to_app_store: false
