workflows:
  ios-workflow:
    name: iOS Build
    environment:
      xcode: latest
    scripts:
      - name: Install Dependencies
        script: |
          npm install  # Install any Node.js dependencies if needed
      - name: Clean the build folder
        script: |
          cd platforms/ios
          xcodebuild clean  # Clean previous builds
      - name: Build the Cordova app
        script: |
          cd platforms/ios
          xcodebuild -project JbPaladinPatriotsClock.xcodeproj -scheme JbPaladinPatriotsClock -configuration Release -archivePath build/JbPaladinPatriotsClock.xcarchive archive
          xcodebuild -exportArchive -archivePath build/JbPaladinPatriotsClock.xcarchive -exportPath build -exportOptionsPlist exportOptions.plist
    artifacts:
      - platforms/ios/build/*.ipa
