workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      groups:
        - appstore_credentials
    scripts:
      - name: Set up code signing
        script: |
          echo $PROVISIONING_PROFILE | base64 --decode > provisioning_profile.mobileprovision
          echo $CERTIFICATE | base64 --decode > certificate.p12
          # Use the variables in your build commands
      - name: Build IPA for distribution
        script: |
          xcode-project build-ipa \
          --project "YourApp.xcworkspace" \
          --scheme "YourAppScheme"
