workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    integrations:
      app_store_connect:
        auth: integration  # Use "integration" as the value
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.jbpaladinpatriotsclock.jbpaladinpatriotsclock  # Your specified bundle identifier
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
          npm ci
      - name: Setup Cordova iOS platform
        script: |
          cordova platform remove ios --nosave
          cordova platform add ios --confirm --no-interactive --noresources --save
      - name: Build IPA for distribution
        script: |
          cordova build ios --release --device
    artifacts:
      - platforms/ios/build/device/*.ipa
    publishing:
      app_store_connect:
        auth: integration  # Use "integration" here as well
        submit_to_testflight: true
        beta_groups:
          - group name 1
          - group name 2
        submit_to_app_store: false
