workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      ios_signing:
        distribution_type: app_store  # or ad_hoc | development | enterprise
        bundle_identifier: com.jbpaladinpatriotsclock.jbpaladinpatriotsclock  # Your app's bundle ID
    scripts:
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/YourApp.xcworkspace" \
            --scheme "YourAppScheme"  # Replace with your Xcode scheme
