workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.jbpaladinpatriotsclock.jbpaladinpatriotsclock
    scripts:
      - name: Clean up previous builds
        script: |
          rm -rf platforms plugins
      - name: Install npm dependencies
        script: |
          npm install
          npm ci
      - name: Setup Cordova iOS platform
        script: |
          cordova platform add ios --confirm --no-interactive
      - name: Update iOS Deployment Target
        script: |
          # Update the Podfile to set the deployment target
          echo "platform :ios, '12.0'" > platforms/ios/Podfile
          # Update the project.pbxproj to set the deployment target
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 11.0;/IPHONEOS_DEPLOYMENT_TARGET = 12.0;/' platforms/ios/JbPaladinPatriotsClock.xcodeproj/project.pbxproj
      - name: Build IPA for distribution
        script: |
          cordova build ios --release --device
    artifacts:
      - build/ios/ipa/*.ipa
