workflows:
  ios-release:
    name: Build iOS Release
    platform: ios
    environment:
      node_version: '16.x'  # or another LTS version of Node.js
    scripts:
      - name: Install Dependencies
        script: |
          npm install
          npm install -g cordova
      - name: Build Cordova Project
        script: |
          cordova platform add ios
          cordova build ios --release --device
