workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.jbpaladinpatriotsclock.jbpaladinpatriotsclock
      APP_STORE_APPLE_ID: XAJF22HXCQ
      XCODE_PROJECT: "platforms/ios/JbPaladinPatriotsClock.xcodeproj"  # Reference to your .xcodeproj
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
          npm ci
      - name: Build ipa for distribution
        script: | 
          cordova build ios --release --device
          xcodebuild -exportArchive \
            -archivePath platforms/ios/build/device/JbPaladinPatriotsClock.xcarchive \
            -exportPath /Users/builder/clone/platforms/ios/build/device \
            -exportOptionsPlist ./export_options.plist  # Updated path
    artifacts:
      - /Users/builder/clone/platforms/ios/build/device/*.ipa
      - /tmp/xcodebuild_logs/*.log
