workflows:
  ios-build:
    name: iOS Build
    environment:
      node: 14 # Specify your Node.js version
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install -g cordova
      - name: Build Cordova App
        script: |
          cordova build ios --release --device
    ios:
    artifacts:
      - platforms/ios/build/device/YourAppName.ipa
