workflows:
  ios_native_workflow:
    name: iOS Native Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.jbpaladinpatriotsclock.jbpaladinpatriotsclock
      vars:
        APP_STORE_APPLE_ID: XAJF22HXCQ
        XCODE_WORKSPACE: "platforms/ios/JbPaladinPatriotsClock.xcworkspace"
        XCODE_SCHEME: "JbPaladinPatriotsClock"
    scripts:
      - name: Remove Cordova iOS Platform
        script: |
          cordova platform remove ios || true  # Remove if exists
      - name: Add Cordova iOS Platform
        script: |
          cordova platform add ios
      - name: Install Node Modules
        script: |
          npm install
      - name: Build iOS
        script: |
          cordova build ios --release --device
    artifacts:
      - platforms/ios/build/device/*.ipa
