workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build iOS
        script: |
          cordova build ios --release
    publishing:
      app_store_connect:
        auth: integration
        submit_to_app_store: true
