workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.jbpaladinpatriotsclock.jbpaladinpatriotsclock
      xcode: latest
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install -g cordova
          npm install
      - name: Verify Deployment Targets
        script: |
          # Check if the deployment target is set to 12.0
          if grep -q "IPHONEOS_DEPLOYMENT_TARGET = 11.0;" platforms/ios/JbPaladinPatriotsClock.xcodeproj/project.pbxproj; then
            echo "Deployment target is still set to 11.0. Please update it to 12.0 in your repository."
            exit 1
          fi
      - name: Set up code signing settings on Xcode project
        script: | 
          xcode-project use-profiles  # Set up code signing profiles
      - name: Build iOS
        script: |
          cordova build ios --release --device
    artifacts:
      - build/ios/*.ipa
