workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2  # Specify the instance type for the build
    integrations:
      app_store_connect: Codemagic  # Integrate with App Store Connect
    environment:
      ios_signing:
        distribution_type: app_store  # Specify the distribution type
        bundle_identifier: com.jbpaladinpatriotsclock.jbpaladinpatriotsclock  # Your app's bundle identifier
    scripts:
      - name: Install npm dependencies
        script: | 
          npm install
          npm ci  # Install dependencies for CI systems
      - name: Install CocoaPods
        script: | 
          sudo gem install cocoapods -v '1.10.1'  # Install a specific version of CocoaPods
      - name: Update Cordova Plugins
        script: | 
          cordova plugin update  # Update all Cordova plugins
      - name: Setup Cordova iOS platform
        script: | 
          cordova platform remove ios --nosave  # Remove existing iOS platform if any
          cordova platform add ios --confirm --no-interactive --noresources --save  # Add iOS platform
      - name: Set Deployment Target for Xcode 11 Compatibility
        script: |
          # Ensure the deployment target is set to at least 11.0 for Xcode 11 compatibility
          sed -i '' 's/<preference name="deployment-target" value=".*" \/>/<preference name="deployment-target" value="11.0" \/>/' config.xml
      - name: Set up code signing settings on Xcode project
        script: | 
          xcode-project use-profiles  # Set up code signing profiles
      - name: Build IPA for distribution
        script: | 
          cordova build ios --release --device  # Build the iOS app
    artifacts:
      - platforms/ios/build/device/*.ipa  # Path to the generated IPA file
      - /tmp/xcodebuild_logs/*.log  # Path to the build logs
