workflows:
  ios-workflow:
    name: iOS Build Workflow
    instance_type: mac_mini_m2
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build iOS
        script: |
          cordova build ios --release
    artifacts:
      - platforms/ios/build/device/*.ipa
