workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.example.yourapp
    scripts:
      - name: Decode provisioning profile
        script: echo $PROVISIONING_PROFILE | base64 --decode > provisioning_profile.mobileprovision
      - name: Decode certificate
        script: echo $CERTIFICATE | base64 --decode > certificate.p12
      - name: Build IPA
        script: |
          xcodebuild -workspace "YourApp.xcworkspace" \
          -scheme "YourAppScheme" \
          -configuration Release \
          -archivePath build/YourApp.xcarchive archive
          xcodebuild -exportArchive \
          -archivePath build/YourApp.xcarchive \
          -exportPath build/YourApp.ipa \
          -exportOptionsPlist ExportOptions.plist
    artifacts:
      - build/*.ipa
