workflows:
  ios_native_workflow:
    name: iOS Native Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.jbpaladinpatriotsclock.jbpaladinpatriotsclock
      vars:
        APP_STORE_APPLE_ID: XAJF22HXCQ
        XCODE_WORKSPACE: "platforms/ios/JbPaladinPatriotsClock.xcworkspace"
        XCODE_SCHEME: "JbPaladinPatriotsClock"
    scripts:
      - name: Set Node.js Version
        script: |
          nvm install 14  # Install Node.js version 14
          nvm use 14      # Use Node.js version 14
      - name: Install npm Dependencies
        script: |
          npm install  # Install npm dependencies needed for your project
      - name: Clean Cordova Project
        script: |
          cordova clean
      - name: Remove iOS Platform
        script: |
          cordova platform rm ios
      - name: Add iOS Platform
        script: |
          cordova platform add ios@latest
      - name: Prepare iOS Platform
        script: |
          cordova prepare ios
      - name: Disable Mac Catalyst in Xcode
        script: |
          sed -i '' 's/ENABLE_MACCATALYST = YES/ENABLE_MACCATALYST = NO/' platforms/ios/build.xcconfig
      - name: Build IPA for Distribution
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --export-options-plist "$CM_BUILD_DIR/export_options.plist"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
