workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      ios_signing:
        distribution_type: app_store  
        provisioning_profiles:
          - "JbPaladinPatriotsClock Distribution Profile"  
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          cd platforms/ios
          pod install
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
          --workspace "$CM_BUILD_DIR/platforms/ios/JbPaladinPatriotsClock.xcworkspace" \
          --scheme "JbPaladinPatriotsClock" \
          --export-options-plist "$CM_BUILD_DIR/export_options.plist"
    artifacts:
      - build/ios/ipa/*.ipa
