workflows:
  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Remove and Re-add iOS Platform
        script: |
          cordova platform rm ios
          cordova platform add ios --no-interactive
      
      - name: Set iOS Deployment Target to 12.0
        script: |
          find platforms/ios -name "project.pbxproj" -exec sed -i '' "s/IPHONEOS_DEPLOYMENT_TARGET = 11.0;/IPHONEOS_DEPLOYMENT_TARGET = 12.0;/g" {} +
          find platforms/ios -name "Podfile" -exec sed -i '' "s/platform :ios, '11.0'/platform :ios, '12.0'/g" {} +
          PLIST_PATH="platforms/ios/*/Info.plist"
          if /usr/libexec/PlistBuddy -c "Print :MinimumOSVersion" $PLIST_PATH; then
            /usr/libexec/PlistBuddy -c "Set :MinimumOSVersion 12.0" $PLIST_PATH
          else
            /usr/libexec/PlistBuddy -c "Add :MinimumOSVersion string 12.0" $PLIST_PATH
          fi
      
      - name: Configure iOS Signing
        script: |
          sed -i '' "s/DevelopmentTeam = \"\";/DevelopmentTeam = \"XAJF22HXCQ\";/g" platforms/ios/JbPaladinPatriotsClock.xcodeproj/project.pbxproj
          sed -i '' "s/\"ProvisioningStyle\" = \"Automatic\";/\"ProvisioningStyle\" = \"Manual\";/g" platforms/ios/JbPaladinPatriotsClock.xcodeproj/project.pbxproj
      
      - name: Install CocoaPods
        script: |
          cd platforms/ios && pod install --repo-update
      
      - name: Build iOS App
        script: |
          cordova build ios --device --release --buildConfig=./build.json
    artifacts:
      - build/ios/iphoneos/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com
